### ISSUE TITLE
Tool not executable in a source environment

### ISSUE THREAD

**Issue by 130s** [kinu-garage/nton_matching#1]
Main tool is not executable yet.

CoS
- [ ] Main tool can become an executable on a Docker container where the repo is sourced (not installed via installer)

**Comment by 130s** [comment]
Struggling to test in a Docker.
The dependent change made in [matching](https://github.com/130s/matching/tree/feature-gjls-volunteer-match) doesn't get installed by `pip` for some reason. As you see below, the new change (a new class `ManyToManyMatching`) is not included in the modules that got installed by `pip`.

<details><summary>Output</summary>

```
# pwd
/cws/src/daffidwilde/matching
root@130s-p16s:/cws/src/daffidwilde/matching# pip install -e .
Obtaining file:///cws/src/daffidwilde/matching
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.19.2 in /root/.local/lib/python3.9/site-packages (from matching==1.4.3) (1.26.3)
Requirement already satisfied: pandas>=2.2.0 in /usr/local/lib/python3.9/site-packages (from matching==1.4.3) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.9/site-packages (from pandas>=2.2.0->matching==1.4.3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.9/site-packages (from pandas>=2.2.0->matching==1.4.3) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.9/site-packages (from pandas>=2.2.0->matching==1.4.3) (2023.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->matching==1.4.3) (1.16.0)
Building wheels for collected packages: matching
  Building editable for matching (pyproject.toml) ... done
  Created wheel for matching: filename=matching-1.4.3-0.editable-py3-none-any.whl size=4846 sha256=7c1067b3f9e315f1793a3d5a088426ce8a4122d80a1cb2707978bc4f975abf60
  Stored in directory: /tmp/pip-ephem-wheel-cache-_l0zgyi6/wheels/88/7e/24/b6e42a8ba1a5c88740efb6ce9d8720209f680275ca11604c54
Successfully built matching
Installing collected packages: matching
  Attempting uninstall: matching
    Found existing installation: matching 1.4.3
    Uninstalling matching-1.4.3:
      Successfully uninstalled matching-1.4.3
Successfully installed matching-1.4.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@130s-p16s:/cws/src/daffidwilde/matching# ack -ir ManyToManyMatching /usr/ 
/usr/local/lib/python3.9/site-packages/matching/matchings.py
67:class ManyToManyMatching(BaseMatching):
```
</details>

How can I test unreleased change? Is there a concept of devel path as opposed to install path (same as Catkin has)? ["Editable installs" (realpython.com)](https://realpython.com/pypi-publish-python-package/#install-your-package-locally) sounds close but I'm not sure yet.

**Comment by 130s** [comment]
Hmm `matching` cannot be found. Even more of a fundamental issue...

```
$ docker run -it --network host    --volume $PATH_LOCAL_WS:/cws/src    --volume /dev:/dev    $DOCKERIMG bash

# cd /cws/src/daffidwilde/matching/ && python3 -m pip install -e .
Obtaining file:///cws/src/daffidwilde/matching
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.19.2 in /root/.local/lib/python3.9/site-packages (from matching==1.4.3) (1.26.3)
Requirement already satisfied: pandas>=2.2.0 in /root/.local/lib/python3.9/site-packages (from matching==1.4.3) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.9/site-packages (from pandas>=2.2.0->matching==1.4.3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /root/.local/lib/python3.9/site-packages (from pandas>=2.2.0->matching==1.4.3) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /root/.local/lib/python3.9/site-packages (from pandas>=2.2.0->matching==1.4.3) (2023.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->matching==1.4.3) (1.16.0)
Building wheels for collected packages: matching
  Building editable for matching (pyproject.toml) ... done
  Created wheel for matching: filename=matching-1.4.3-0.editable-py3-none-any.whl size=4846 sha256=4dda4aee5763ecc83af6c09e73aaf711bac01e0ceb6ef46ad9222a871b857ec1
  Stored in directory: /tmp/pip-ephem-wheel-cache-rdrhz2ew/wheels/88/7e/24/b6e42a8ba1a5c88740efb6ce9d8720209f680275ca11604c54
Successfully built matching
Installing collected packages: matching
  Attempting uninstall: matching
    Found existing installation: matching 1.4.3
    Uninstalling matching-1.4.3:
      Successfully uninstalled matching-1.4.3
Successfully installed matching-1.4.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@130s-p16s:/cws/src/daffidwilde/matching# ipython3 
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
:
In [1]: from matching import BaseGame, ManyToManyMatching
   ...: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f74c1eeeb618> in <module>
----> 1 from matching import BaseGame, ManyToManyMatching

ModuleNotFoundError: No module named 'matching'
```

**Comment by 130s** [comment]
Ok. The module in question is installed in `/usr/local/lib/python3.9/site-packages`, which Python (ipython) doesn't seem to be looking into (although it does look into `dist-packages`).

```
$ docker run -it --network host    --volume $PATH_LOCAL_WS:/cws/src    --volume /dev:/dev    $DOCKERIMG bash

root@130s-p16s:/# cd /cws/src/daffidwilde/matching/ && python3 -m pip install .
Processing /cws/src/daffidwilde/matching
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.19.2 in /root/.local/lib/python3.9/site-packages (from matching==1.4.3) (1.26.3)
Requirement already satisfied: pandas>=2.2.0 in /root/.local/lib/python3.9/site-packages (from matching==1.4.3) (2.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.9/site-packages (from pandas>=2.2.0->matching==1.4.3) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /root/.local/lib/python3.9/site-packages (from pandas>=2.2.0->matching==1.4.3) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in /root/.local/lib/python3.9/site-packages (from pandas>=2.2.0->matching==1.4.3) (2023.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas>=2.2.0->matching==1.4.3) (1.16.0)
Building wheels for collected packages: matching
  Building wheel for matching (pyproject.toml) ... done
  Created wheel for matching: filename=matching-1.4.3-py3-none-any.whl size=30330 sha256=51264261be5c0a588a7e7005a920b752bd38e5210e4c78e1216cc6aa58a1692c
  Stored in directory: /tmp/pip-ephem-wheel-cache-5_67aods/wheels/88/7e/24/b6e42a8ba1a5c88740efb6ce9d8720209f680275ca11604c54
Successfully built matching
Installing collected packages: matching
  Attempting uninstall: matching
    Found existing installation: matching 1.4.3
    Uninstalling matching-1.4.3:
      Successfully uninstalled matching-1.4.3
Successfully installed matching-1.4.3
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@130s-p16s:/cws/src/daffidwilde/matching# ipython3 
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.20.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from matching import BaseGame, ManyToManyMatching
   ...: 
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-f74c1eeeb618> in <module>
----> 1 from matching import BaseGame, ManyToManyMatching

ModuleNotFoundError: No module named 'matching'

In [2]:  import sys

In [3]: sys.path
Out[3]: 
['/usr/bin',
 '/usr/lib/python39.zip',
 '/usr/lib/python3.9',
 '/usr/lib/python3.9/lib-dynload',
 '',
 '/root/.local/lib/python3.9/site-packages',
 '/usr/local/lib/python3.9/dist-packages',
 '/usr/lib/python3/dist-packages',
 '/usr/lib/python3/dist-packages/IPython/extensions',
 '/root/.ipython']

[1]+  Stopped                 ipython3
root@130s-p16s:/cws/src/daffidwilde/matching# find /usr/ -iname matching
/usr/local/lib/python3.9/site-packages/matching
```

`pip install` with `--user` option seems to resolve this :thinking:

```
# find / -iname matching
/root/.local/lib/python3.9/site-packages/matching
/usr/local/lib/python3.9/site-packages/matching
```
<details><summary>At least import error stopped.</summary>

```
In [1]: from matching import BaseGame, ManyToManyMatching
   ...: 
Traceback (most recent call last):

  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3427, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-f74c1eeeb618>", line 1, in <module>
    from matching import BaseGame, ManyToManyMatching

  File "/root/.local/lib/python3.9/site-packages/matching/__init__.py", line 11, in <module>
    from .matchings import ManyToManyMatching, MultipleMatching, SingleMatching

  File "/root/.local/lib/python3.9/site-packages/matching/matchings.py", line 105
    def set(self, player, new):
                               ^
IndentationError: expected an indented block
```
</details>

**Comment by 130s** [comment]
<details><summary>Hmm...</summary>

```
# gjls_match 
/cws/src/daffidwilde/matching/src/matching/matchings.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas
Traceback (most recent call last):
  File "/usr/local/bin/gjls_match", line 5, in <module>
    from n_to_n_matching.__main__ import main
ImportError: cannot import name 'main' from 'n_to_n_matching.__main__' (/cws/src/130s/nton_matching/n_to_n_matching/src/n_to_n_matching/__main__.py)
```
```
# more /usr/local/bin/gjls_match
#!/usr/local/bin/python3
# -*- coding: utf-8 -*-
import re
import sys
from n_to_n_matching.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
</details>

`__main__.py` indeed defines `main()`, in addition to `if __name__ == "__main__":` in [realpython.com](https://realpython.com/pypi-publish-python-package/#understand-the-reader-code). That seems redundant, but don't want to argue here for now. Defined `main` and got this passed.

**Comment by 130s** [comment]
> `__main__.py` indeed defines `main()`, in addition to `if __name__ == "__main__":` in [realpython.com](https://realpython.com/pypi-publish-python-package/#understand-the-reader-code). That seems redundant, but don't want to argue here for now. Defined `main` and got this passed.

Ah, that was just b/c I defined in `pyproject.toml` to look for a method called `main` by:
```
gjls_match = "n_to_n_matching.__main__:main"
```
The following still seems to work with seeking `__main__` as expected.
```
gjls_match = "n_to_n_matching.__main__:__main__"
```

**Comment by 130s** [comment]
<details><summary>One of a dep not found.</summary>

```
# gjls_match 
/cws/src/daffidwilde/matching/src/matching/matchings.py:3: DeprecationWarning: 
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
        
  import pandas

Traceback (most recent call last):
  File "/usr/local/bin/gjls_match", line 5, in <module>
    from n_to_n_matching.__main__ import __main__
  File "/cws/src/130s/nton_matching/n_to_n_matching/src/n_to_n_matching/__main__.py", line 1, in <module>
    from n_to_n_matching.test_main import test_1
  File "/cws/src/130s/nton_matching/n_to_n_matching/src/n_to_n_matching/test_main.py", line 1, in <module>
    from n_to_n_matching.matcher import GjVolunteerAllocationGame
  File "/cws/src/130s/nton_matching/n_to_n_matching/src/n_to_n_matching/matcher.py", line 31, in <module>
    from n_to_n_matching.util import Util
  File "/cws/src/130s/nton_matching/n_to_n_matching/src/n_to_n_matching/util.py", line 19, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

Debug code shows:
```
Python sys.path: ['/usr/local/bin', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/root/.local/lib/python3.9/site-packages', '/cws/src/daffidwilde/matching/src', '/usr/local/lib/python3.9/site-packages', '/cws/src/130s/nton_matching/n_to_n_matching/src']
```

AFAIK, yaml module is installed via `apt install python3-yaml`. So it laying down in the global `/usr/lib/python3/dist-packages` makes sense.
```
# find / -iname *py*yaml*
/usr/lib/python3/dist-packages/PyYAML-5.3.1.egg-info
/usr/share/doc/python3-yaml
/var/lib/dpkg/info/python3-yaml.prerm
/var/lib/dpkg/info/python3-yaml.postinst
/var/lib/dpkg/info/python3-yaml.list
/var/lib/dpkg/info/python3-yaml.md5sums
```
</details>

Why is my Python executable not looking into the global `dist-packages`?

Can `pip` package NOT depend on `apt` packages??? Hm, looks like "pure" PyPI package cannot ([serverfault.com#1113454](https://serverfault.com/questions/1113454/) (Then it's just catkin/colcon handled the dependency so nicely so that a package can depend on both pip/apt pkgs).

For now I'll just switch to all `pip` pkgs during the dev.

**Comment by 130s** [comment]
> The following still seems to work with seeking `__main__` as expected.
> 
> ```
> gjls_match = "n_to_n_matching.__main__:__main__"
> ```

Wait, no, there's no method called `__main__` in `__main__.py`, so this results in an error. It's ok, just create `main()`.

**Comment by 130s** [comment]
Resolved by https://github.com/kinu-garage/nton_matching/pull/4
